directory: charts
repositories:
- name: jetstack
  url: https://charts.jetstack.io
requires:
- chart: jetstack/cert-manager
  version: v1.19.2
- chart: jetstack/trust-manager
  version: 0.20.3
version: 1
